=== pesc-org/technical-advisory-board/Submissions/2016-04-11 Submission/Archive/definition_v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 3 (x64) (http://www.altova.com) by NEIL SCHMITZ (ACT, INC.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:def="urn:org:pesc:definition_v1.0.0" targetNamespace="urn:org:pesc:definition_v1.0.0" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="DefinitionList" type="def:DefinitionType">
		<xs:annotation>
			<xs:documentation>A set of element and type defintions</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="DefinitionType">
		<xs:sequence>
			<xs:element name="Line" type="def:LineType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LineType">
		<xs:sequence>
			<xs:element name="Term" type="xs:string"/>
			<xs:element name="Type" type="xs:string"/>
			<xs:element name="Definition" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== pesc-org/technical-advisory-board/Submissions/2016-04-11 Submission/Archive/ePort definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<def:DefinitionList xsi:schemaLocation="urn:org:pesc:definition_v1.0.0 definition_v1.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:def="urn:org:pesc:definition_v1.0.0">
	<Line>
		<Term>TransmissionData</Term>
		<Type>xs:element</Type>
		<Definition>This element provides a logical grouping of elements related to Transmission information.</Definition>
	</Line>
	<Line>
		<Term>Profile</Term>
		<Type>xs:element</Type>
		<Definition>Student identification and demographical information.</Definition>
	</Line>
	<Line>
		<Term>Events</Term>
		<Type>xs:element</Type>
		<Definition>Attributes describing an event as stored in a student’s portfolio. An event could be related to an academic course or program or a life/work/education event or experience.</Definition>
	</Line>
	<Line>
		<Term>Goals</Term>
		<Type>xs:element</Type>
		<Definition>A student’s goals and related action plans as stored in the student’s portfolio. Active and completed goals can be defined.</Definition>
	</Line>
	<Line>
		<Term>Artifacts</Term>
		<Type>xs:element</Type>
		<Definition>The Artifacts component provides a flexible structure for storing artifacts related to many of the other components of the schema. For example, artifacts could be related to events, goals, education, employment, or competencies. Artifacts can represent documents uploaded into the eportfolio or online documents stored at a specific URL.</Definition>
	</Line>
	<Line>
		<Term>Comments</Term>
		<Type>xs:element</Type>
		<Definition>The Comments component supports the related Events and Artifacts components providing a structure for owner, advisor, teacher, professor, peer, and parent/guardian eportfolio comments that can be connected to other related objects. The same comment can refer to multiple objects in the instance.</Definition>
	</Line>
	<Line>
		<Term>Education</Term>
		<Type>xs:element</Type>
		<Definition>Contains score and interpretive data for all the tests reported in the test score report</Definition>
	</Line>
	<Line>
		<Term>EmploymentHistory</Term>
		<Type>xs:element</Type>
		<Definition>The Employment History component supports data related to jobs at multiple employers and a place for ObjectLinks to artifacts such as résumés stored in the student’s portfolio. This employment history data could be used by a system as part of a résumé function.</Definition>
	</Line>
	<Line>
		<Term>Competencies</Term>
		<Type>xs:element</Type>
		<Definition>The Competencies component provides a general structure for data related to the eportfolio owner’s competencies and skills. A general structure was defined to support the numerous skill and competency models and taxonomies in existence.</Definition>
	</Line>
	<Line>
		<Term>Networks</Term>
		<Type>xs:element</Type>
		<Definition>The Networks component includes elements to describe the eportfolio owner’s networks and references.</Definition>
	</Line>
	<Line>
		<Term>LicensesAndCredentials</Term>
		<Type>xs:element</Type>
		<Definition>The Licenses and Credentials component defines the eportfolio owner’s licenses—including information on the currency of the license and the issuing authority—as well as industry-recognized credentials.</Definition>
	</Line>
	<Line>
		<Term>MilitaryHistory</Term>
		<Type>xs:element</Type>
		<Definition>The Military History component provides a summary of the eportfolio owner’s military employment experiences.</Definition>
	</Line>
	<Line>
		<Term>CareerAssessments</Term>
		<Type>xs:element</Type>
		<Definition>The Career Assessments component provides a structure for supporting a range of career assessment results including two standard Department of Labor assessments commonly used in education and workforce development settings.</Definition>
	</Line>
	<Line>
		<Term>Lists</Term>
		<Type>xs:element</Type>
		<Definition>The Lists component defines a flexible structure for transmitting or exporting lists of stored items that are typically part of career and education planning in a student’s portfolio. This includes lists of careers of interest, postsecondary programs and majors of interest, postsecondary schools of interest, and scholarships.</Definition>
	</Line>
	<Line>
		<Term>UserDefinedExtensions</Term>
		<Type>xs:element</Type>
		<Definition>This is used to create a place holder for the Unique Data which is defined by the VendorCode and IdentifierCode.</Definition>
	</Line>
	<Line>
		<Term>NoteMessage</Term>
		<Type>xs:element</Type>
		<Definition> Note Message: Entities may use this field to store information not otherwise tracked on a loan.</Definition>
	</Line>
	<Line>
		<Term>Name</Term>
		<Type>xs:element</Type>
		<Definition>The title given to someone, usually at birth. The name of the author of the comment.</Definition>
	</Line>
	<Line>
		<Term>Gender</Term>
		<Type>xs:element</Type>
		<Definition>The sex designation of a person.</Definition>
	</Line>
	<Line>
		<Term>Birth</Term>
		<Type>xs:element</Type>
		<Definition>Information about the delivery, creation or beginning of life of a person.</Definition>
	</Line>
	<Line>
		<Term>SSN</Term>
		<Type>xs:element</Type>
		<Definition>The person's U.S. Social Security Number.</Definition>
	</Line>
	<Line>
		<Term>SIN</Term>
		<Type>xs:element</Type>
		<Definition>The Social Insurance Number (Canadian) of the portfolio owner.</Definition>
	</Line>
	<Line>
		<Term>NSN</Term>
		<Type>xs:element</Type>
		<Definition>The National Student Number (Canadian) of the portfolio owner.</Definition>
	</Line>
	<Line>
		<Term>AgencyAssignedID</Term>
		<Type>xs:element</Type>
		<Definition>The ID assigned by an agency to the person (student or borrower).</Definition>
	</Line>
	<Line>
		<Term>Contacts</Term>
		<Type>xs:element</Type>
		<Definition>This element provides a logical grouping of elements related to contact information.</Definition>
	</Line>
	<Line>
		<Term>Citizenship</Term>
		<Type>xs:element</Type>
		<Definition>Attributes of a person's qualifications to become or to have become a citizen of a country.</Definition>
	</Line>
	<Line>
		<Term>EthnicityRace</Term>
		<Type>xs:element</Type>
		<Definition>The cultural, tribal or national background of a person.</Definition>
	</Line>
	<Line>
		<Term>ParentGuardian</Term>
		<Type>xs:element</Type>
		<Definition>To be deprecated in a future release</Definition>
	</Line>
	<Line>
		<Term>HSTranscript</Term>
		<Type>xs:element</Type>
		<Definition>A portfolio owner&apos;s high school transcript.</Definition>
	</Line>
	<Line>
		<Term>CollegeTranscript</Term>
		<Type>xs:element</Type>
		<Definition>A portfolio owner&apos;s College transcript.</Definition>
	</Line>
	<Line>
		<Term>TestScoreReport</Term>
		<Type>xs:element</Type>
		<Definition>Information about the attribuites, accomplishments and test scores of a set of students</Definition>
	</Line>
	<Line>
		<Term>ApplicationForAdmission</Term>
		<Type>xs:element</Type>
		<Definition>A portfolio owner’s application to a postsecondary institution.</Definition>
	</Line>
	<Line>
		<Term>PostsecondaryProgram</Term>
		<Type>xs:element</Type>
		<Definition>A portfolio owner&apos;s postsecondary program; both completed and in-progress.</Definition>
	</Line>
	<Line>
		<Term>SecondaryEducation</Term>
		<Type>xs:element</Type>
		<Definition>A portfolio owner&apos;s high school education details.</Definition>
	</Line>
	<Line>
		<Term>OtherLearning</Term>
		<Type>xs:element</Type>
		<Definition>A portfolio owner&apos;s other learning experiences.</Definition>
	</Line>
	<Line>
		<Term>GoalID</Term>
		<Type>xs:element</Type>
		<Definition>An identifier for a goal.</Definition>
	</Line>
	<Line>
		<Term>GoalCode</Term>
		<Type>xs:element</Type>
		<Definition>The type of goal.</Definition>
	</Line>
	<Line>
		<Term>GoalTitle</Term>
		<Type>xs:element</Type>
		<Definition>The title or label for the goal.</Definition>
	</Line>
	<Line>
		<Term>GoalDescription</Term>
		<Type>xs:element</Type>
		<Definition>A brief description of the goal.</Definition>
	</Line>
	<Line>
		<Term>GoalTargetDate</Term>
		<Type>xs:element</Type>
		<Definition>The target date for achieving the goal.</Definition>
	</Line>
	<Line>
		<Term>GoalCompletionDate</Term>
		<Type>xs:element</Type>
		<Definition>The actual date when the goal was achieved.</Definition>
	</Line>
	<Line>
		<Term>GoalObjectLink</Term>
		<Type>xs:element</Type>
		<Definition>An object link to another node or object related to this goal. For example, it could connect this goal to a related artifact stored in the portfolio.</Definition>
	</Line>
	<Line>
		<Term>GoalActionPlanStep</Term>
		<Type>xs:element</Type>
		<Definition>Details describing the attributes of a single step in an action plan related to a goal set by the portfolio owner.</Definition>
	</Line>
	<Line>
		<Term>ObjectPath</Term>
		<Type>xs:element</Type>
		<Definition>Path expression specifying a node within this XML document. The node specified by the expression has a parent or child relationship to the current node/object.</Definition>
	</Line>
	<Line>
		<Term>ObjectRelationCode</Term>
		<Type>xs:element</Type>
		<Definition>The relationship between the linked node/object and the current node/object.</Definition>
	</Line>
	<Line>
		<Term>ObjectID</Term>
		<Type>xs:element</Type>
		<Definition>An alternate identifier, unique within this component, to the node/object within this XML document that has a relationship to the current node. Can be used by applications to reference the related node. Examples of ID elements in the schema: EventID, ArtifactID, CommentID, GoalID, and StepID.</Definition>
	</Line>
	<Line>
		<Term>EventID</Term>
		<Type>xs:element</Type>
		<Definition>An identifier for an event.</Definition>
	</Line>
	<Line>
		<Term>EventClassification</Term>
		<Type>xs:element</Type>
		<Definition>The classification of an event.</Definition>
	</Line>
	<Line>
		<Term>EventTitle</Term>
		<Type>xs:element</Type>
		<Definition>The name, title, or label of the event.</Definition>
	</Line>
	<Line>
